[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "python3 -m pip install --no-cache-dir -r requirements.txt"
]
